name: shouldideploy
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.1.1 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  get_it: ^7.6.7
  http: ^1.1.0
  riverpod_annotation: ^2.3.3

dev_dependencies:
  build_runner:
  custom_lint:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  full_coverage: ^1.0.0
  golden_toolkit: ^0.15.0
  mocktailx: ^0.0.5
  riverpod_generator: ^2.3.9
  riverpod_lint: ^2.3.7

flutter:
  uses-material-design: true
