name: PR Validator

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - labeled
      - unlabeled
      - edited
      - ready_for_review

jobs:
  check-pr-title-cc:
    runs-on: ubuntu-latest

    steps:
      - name: Conventional PR Title Verify
        uses: satvik-s/pr-title-check@1.3.0
        continue-on-error: true
        with:
          pattern: '(fix|feat|chore|docs|style|refactor|perf|test|bump|ci|revert): (\[[A-Z]{3}-[0-9]{3,5}\]) (?:\w+\b\W*){2,8}$'

  check-pr-title-release:
    runs-on: ubuntu-latest

    steps:
      - name: Release PR Title Verify
        uses: satvik-s/pr-title-check@1.3.0
        continue-on-error: true
        with:
          pattern: "(Release/)"

  can-continue:
    runs-on: ubuntu-latest
    needs: [check-pr-title-cc, check-pr-title-release]
    if: always() && (needs.check-pr-title-cc.result == 'success' || needs.check-pr-title-release.result == 'success')

  analyze-and-test:
    runs-on: ubuntu-latest
    needs: can-continue
    if: ${{ !github.event.pull_request.draft }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.19.0

      - name: Install dependencies
        run: flutter pub get

      - name: Verify formatting
        run: dart format --output=none --set-exit-if-changed .

      - name: Analyze project source
        run: flutter analyze

      - name: Run tests
        run: flutter test
