name: PR Validator

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - labeled
      - unlabeled
      - edited
      - ready_for_review

jobs:
  check-pr-title:
    runs-on: ubuntu-latest

    steps:
      - name: PR Title Verify
        uses: satvik-s/pr-title-check@1.3.0
        with:
          pattern: '(fix|feat|chore|docs|style|refactor|perf|test|bump|ci|revert): (\[[A-Z]{3}-[0-9]{3,5}\]) (?:\w+\b\W*){2,8}$'

  print-pr-title-example:
    runs-on: ubuntu-latest
    needs: check-pr-title
    if: ${{ always() && needs.check-pr-title.result == 'failure' }}
    steps:
      - name: Print PR Title example
        run: |
          echo "Please rename your PR following this pattern: "
          echo "type: [JIRA-ISSUE] Description with a least three words"
          echo "Something like this: chore: [ABC-123] Story description following jira issue"

  analyze-and-test:
    runs-on: ubuntu-latest
    needs: check-pr-title
    if: ${{ !github.event.pull_request.draft }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.19.0

      - name: Install dependencies
        run: flutter pub get

      - name: Verify formatting
        run: dart format --output=none --set-exit-if-changed .

      - name: Analyze project source
        run: flutter analyze

      - name: Run tests
        run: flutter test
